# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'docs|conf|.git'
default_stages: [commit]
fail_fast: true
default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.4.6'
    hooks:
    # Run the linter
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      pass_filenames: false
      # Run the formatter
    - id: ruff-format
      pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: '^(.*\.md|Makefile|\.idea/|ui/dev/)$'
    - id: trailing-whitespace
      language_version: python3
      exclude: '^(.*\.md|Makefile)$'

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      args: [ "." ]
      types: [python]
      language: system
      pass_filenames: false
